export const IPC_STATES_REQ = {
    GET_VOICE_CONNECTION_READINESS: 'GET_VOICE_CONNECTION_READINESS',
    PAUSE_VOICE_CONNECTION: 'PAUSE_VOICE_CONNECTION',
    RESUME_VOICE_CONNECTION: 'RESUME_VOICE_CONNECTION',
    SKIP_VOICE_CONNECTION: 'SKIP_VOICE_CONNECTION',
    START_PLAYER_PROCESS: 'START_PLAYER_PROCESS',
}

export const IPC_STATES_RESP = {
    SONG_SKIPPED: 'SONG_SKIPPED',
    SONG_PAUSED: 'SONG_PAUSED',
    SONG_RESUMED: 'SONG_RESUMED',
    SONG_COMPLETED: 'SONG_COMPLETED', // when track played by separate process is completed
    VOICE_CONNECTION_READY: 'VOICE_CONNECTION_READY', // when the separate process bot is properly connected to the audio channel
}

