
export const IPC_STATES_REQ = {
    GET_VOICE_CONNECTION_READINESS: 'GET_VOICE_CONNECTION_READINESS',
    PAUSE_VOICE_CONNECTION: 'PAUSE_VOICE_CONNECTION',
    RESUME_VOICE_CONNECTION: 'RESUME_VOICE_CONNECTION',
    SKIP_VOICE_CONNECTION: 'SKIP_VOICE_CONNECTION',
    LEAVE_VOICE_CONNECTION: 'LEAVE_VOICE_CONNECTION',
    START_PLAYER_PROCESS: 'START_PLAYER_PROCESS',
}

export const IPC_STATES_RESP = {
    SONG_SKIPPED: 'SONG_SKIPPED',
    SONG_PLAYING: 'SONG_PLAYING',
    SONG_PAUSED: 'SONG_PAUSED',
    SONG_RESUMED: 'SONG_RESUMED',
    SONG_IDLE: 'SONG_IDLE_OR_COMPLETED', // when track played by separate process is idle/complete
    VOICE_CONNECTION_READY: 'VOICE_CONNECTION_READY', // when the separate process bot is properly connected to the audio channel
    VOICE_CONNECTION_LEAVED: 'VOICE_CONNECTION_LEAVED',
    REMOVE_GUILD_SUBSCRIPTION: 'REMOVE_GUILD_SUBSCRIPTION'
}

